### ISSUE TITLE
how to use it

### ISSUE THREAD

**Issue by ZhengxunWu** [ajantis/java-crdt#2]
hi, I am wondering how to use the crdt in my android studio.

**Comment by ajantis** [comment]
Hey @ZhengxunWu !

Unfortunately, this library is not published to any public artefact repositories (e.g. Maven Central). 
Thus, one way would be building and installing it locally on your machine (`mvn install`) if you just want to play with it first. 
For a more serious use-case, I suggest either forking it (the license is rather permissive - MIT) or just deploying to the central artefact repository of your choice. Then you simply need to use your dependency management tool (assuming it to be gradle if you use Android...) to reference that lib. 

Hope this helps.

Best,
-Dmitry
